FROM java:8
EXPOSE 7072
ADD /target/bank-customer-info-service-0.0.1-SNAPSHOT.jar bank-customer-info-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","bank-customer-info-service-0.0.1-SNAPSHOT.jar"]
