FROM java:8
EXPOSE 7071
ADD /target/bank-customer-account-service-0.0.1-SNAPSHOT.jar bank-customer-account-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","bank-customer-account-service-0.0.1-SNAPSHOT.jar"]
