FROM java:8
EXPOSE 7073
ADD /target/bank-customer-transaction-service-0.0.1-SNAPSHOT.jar bank-customer-transaction-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","bank-customer-transaction-service-0.0.1-SNAPSHOT.jar"]
